challenge3/force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>動物</label>
    <nameField>
        <label>動物名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

challenge3/force-app/main/default/objects/Animal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>説明</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

challenge3/force-app/main/default/objects/Animal__c/fields/Endangered__c.field-meta.xml
<CustomField>
    <fullName>Endangered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>絶滅危惧種</label>
    <type>Checkbox</type>
</CustomField>

challenge3/force-app/main/default/objects/Animal__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>画像</label>
    <type>Url</type>
</CustomField>

challenge3/force-app/main/default/objects/Park__c/Park__c.object-meta.xml
<CustomObject>
    <label>公園</label>
    <nameField>
        <label>公園名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

challenge3/force-app/main/default/objects/ParkAnimalRelation__c/ParkAnimalRelation__c.object-meta.xml
<CustomObject>
    <label>公園での目撃情報</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>目撃情報番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

challenge3/force-app/main/default/objects/ParkAnimalRelation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>動物</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>公園での目撃情報</relationshipLabel>
    <relationshipName>Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

challenge3/force-app/main/default/objects/ParkAnimalRelation__c/fields/Park__c.field-meta.xml
<CustomField>
    <fullName>Park__c</fullName>
    <label>公園</label>
    <referenceTo>Park__c</referenceTo>
    <relationshipLabel>公園での目撃情報</relationshipLabel>
    <relationshipName>Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

challenge3/force-app/main/default/classes/AnimalController.cls
public with sharing class AnimalController {
    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getAnimalsByParkId(String parkId) {
        List<ParkAnimalRelation__c> relations = [
            SELECT Animal__r.Id, Animal__r.Name, Animal__r.Description__c, Animal__r.Endangered__c, Animal__r.Image__c
            FROM ParkAnimalRelation__c
            WHERE Park__c = :parkId
        ];
        List<Animal__c> result = new List<Animal__c>();
        for (ParkAnimalRelation__c r : relations) {
            result.add(
                new Animal__c(
                Id = r.Animal__r.Id,
                Name = r.Animal__r.Name,
                Description__c = r.Animal__r.Description__c,
                Endangered__c = r.Animal__r.Endangered__c,
                Image__c = r.Animal__r.Image__c
                )
            );
        }
        return result;
    }
}