challenge4/force-app/main/default/objects/Fridge_History__c/Fridge_History__c.object-meta.xml
<CustomObject>
    <label>冷蔵庫の開閉ログ</label>
    <nameField>
        <displayFormat>FH-{00000}</displayFormat>
        <label>ログ番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

challenge4/force-app/main/default/objects/Fridge_History__c/fields/badgeId__c.field-meta.xml
<CustomField>
    <fullName>badgeId__c</fullName>
    <label>バッジID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

challenge4/force-app/main/default/objects/Fridge_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>冷蔵庫の開閉履歴</relationshipLabel>
    <relationshipName>Fridge_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

challenge4/force-app/main/default/objects/Fridge_History__c/fields/fridgeId__c.field-meta.xml
<CustomField>
    <fullName>fridgeId__c</fullName>
    <label>冷蔵庫ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

challenge4/force-app/main/default/objects/Fridge_Log__e/Fridge_Log__e.object-meta.xml
<CustomObject>
    <label>冷蔵庫の開閉</label>
</CustomObject>

challenge4/force-app/main/default/objects/Fridge_Log__e/fields/badgeId__c.field-meta.xml
<CustomField>
    <fullName>badgeId__c</fullName>
    <label>badgeId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

challenge4/force-app/main/default/objects/Fridge_Log__e/fields/employeeName__c.field-meta.xml
<CustomField>
    <fullName>employeeName__c</fullName>
    <label>employeeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

challenge4/force-app/main/default/objects/Fridge_Log__e/fields/fridgeId__c.field-meta.xml
<CustomField>
    <fullName>fridgeId__c</fullName>
    <label>fridgeId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

challenge4/force-app/main/default/classes/FridgeLogTriggerHandler.cls
public class FridgeLogTriggerHandler {
    public static void handleEvent(List<Fridge_Log__e> events) {
        //簡便のため、すべてのロジックをハンドラクラス内に記載しています。
        
        Map<String, Set<FridgeLogEvent>> employeeNameToEventsMap = new Map<String, Set<FridgeLogEvent>>();
        for (Fridge_Log__e event : events) {
            FridgeLogEvent fle = new FridgeLogEvent(event.ReplayId, event.badgeId__c, event.fridgeId__c);
            if (employeeNameToEventsMap.containsKey(event.employeeName__c)) {
                employeeNameToEventsMap.get(event.employeeName__c).add(fle);
                } else {
                employeeNameToEventsMap.put(event.employeeName__c, new Set<FridgeLogEvent>{ fle });
            }
        }
        List<Contact> contacts = [
            SELECT Name
            FROM Contact
            WHERE Name IN :employeeNameToEventsMap.keySet()
        ];
        List<Fridge_History__c> fridgeHistoryRecords =  new List<Fridge_History__c>();
        for (Contact contact : contacts) {
            for (FridgeLogEvent fle : employeeNameToEventsMap.get(contact.Name)) {
                Fridge_History__c fh = new Fridge_History__c(
                    Contact__c = contact.Id,
                    BadgeId__c = fle.badgeId,
                    FridgeId__c = fle.fridgeId
                );
                fridgeHistoryRecords.add(fh);
            }
        }

        if (!fridgeHistoryRecords.isEmpty()) {
            insert fridgeHistoryRecords;
        }
    }

    public class FridgeLogEvent {
        public String replayId;
        public String badgeId;
        public String fridgeId;
        public FridgeLogEvent(String replayId, String badgeId, String fridgeId) {
            this.replayId = replayId;
            this.badgeId = badgeId;
            this.fridgeId = fridgeId;
        }

        public Boolean equals(Object obj) {
            if (obj instanceof FridgeLogEvent) {
                FridgeLogEvent e = (FridgeLogEvent)obj;
                return (this.replayId.equals(e.replayId));
            }
            return false;
        }

        public Integer hashCode() {
            return 31 + Integer.valueOf(replayId);
        }
    }
}